# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
default-extensions:
  - OverloadedStrings
  - DataKinds
  - TemplateHaskell
  - TypeOperators

benchmarks:
  spyglass-benchmarks:
    dependencies:
    - base
    - spyglass
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: spyglass is a new Haskeleton package.
executables:
  spyglass:
    dependencies:
    - base
    - spyglass
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.rst
- stack.yaml
ghc-options: -Wall
github: githubuser/spyglass
library:
  dependencies:
  - base
  - aeson
  - servant-server
  - wai
  - wai-extra
  - warp
  - text
  - containers
  - transformers
  - mtl
  - stm
  source-dirs: library
license: MIT
maintainer: Author name here
name: spyglass
synopsis: A new Haskeleton package.
tests:
  spyglass-test-suite:
    dependencies:
    - base
    - spyglass
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
