# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: spyglass
version: '0.0.0'
github: "githubuser/spyglass"
license: MIT
author: "Author name here"
maintainer: "Author name here"
synopsis: A new Haskeleton package.
description: spyglass is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

default-extensions:
  - OverloadedStrings

library:
  dependencies:
  - base
  - Spock
  - mtl
  - text
  - containers
  - stm
  source-dirs: library

executables:
  spyglass:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - spyglass
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  spyglass-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - spyglass
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  spyglass-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - spyglass
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
