# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: spyglass
version: '0.0.0'
github: "huseyinyilmaz/spyglass"
license: MIT
author: "Huseyin Yilmaz"
maintainer: "Huseyin Yilmaz"
synopsis: In memmory autocomplete engine with rest interface.
description: spyglass is an in-memory autocomplete engine that serves its data using a REST interface.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.rst
- stack.yaml

ghc-options: -Wall

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - FlexibleContexts
  - GADTs
  - RankNTypes
  - DuplicateRecordFields
  - GeneralizedNewtypeDeriving
library:
  dependencies:
  - base
  - Spock
  - mtl
  - syb
  - text
  - containers
  - stm
  - bytestring-trie
  - bytestring
  - http-api-data
  - aeson
  - wai
  - wai-extra
  - http-types
  - directory
  - yaml
  - ekg
  - wai-middleware-metrics

  - tasty
  - tasty-hspec
  - hspec
  - hspec-wai
  - Spock
  - aeson

  source-dirs: library

executables:
  spyglass:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - spyglass
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  spyglass-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - spyglass
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  spyglass-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - spyglass
    - tasty
    - tasty-hspec
    - hspec
    - hspec-wai
    - Spock
    - aeson
    - wai
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
