# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: spyglass
version: '0.0.0'
github: "huseyinyilmaz/spyglass"
license: MIT
author: "Huseyin Yilmaz"
maintainer: "Huseyin Yilmaz"
synopsis: In memmory autocomplete engine with rest interface.
description: spyglass is an in-memory autocomplete engine that serves its data using a REST interface.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.rst
- stack.yaml

ghc-options: -Wall

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - FlexibleContexts
  - GADTs
  - RankNTypes
  - DuplicateRecordFields
  - GeneralizedNewtypeDeriving
  - BangPatterns
library:
  dependencies:
  - base
  - mtl
  - syb
  - text
  - containers
  - stm
  - bytestring-trie
  - bytestring
  - http-api-data
  - aeson
  - wai
  - warp
  - wai-extra
  - http-types
  - directory
  - yaml
  - ekg
  - wai-middleware-metrics
  - time

  - aeson
  - tasty
  - tasty-hspec
  - hspec
  - hspec-wai
  - base64-bytestring

  - criterion


  source-dirs: library

executables:
  spyglass:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - spyglass
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    - -O2

benchmarks:
  spyglass-benchmarks:
    source-dirs:
      - benchmark/speed
    main: Main.hs
    dependencies:
    - base
    - spyglass
    - criterion
    - wai
    - wai-extra
    - aeson
    - bytestring

    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  spyglass-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - aeson
    - base
    - base64-bytestring
    - bytestring
    - hspec
    - hspec-wai
    - spyglass
    - tasty
    - tasty-hspec
    - wai
    - wai-extra

    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

nix:
  enable: false
  packages:
  # - fcgi
  - zlib
